// <auto-generated />
using System;
using MessengerServer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MessengerServer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MessengerServer.Chat", b =>
                {
                    b.Property<decimal>("SUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<decimal>("OwnerSUID")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("SUID");

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("MessengerServer.Message", b =>
                {
                    b.Property<decimal>("SUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<int>("ContentType")
                        .HasColumnType("integer");

                    b.Property<decimal>("Membership")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("Owner")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SUID");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("MessengerServer.Participant", b =>
                {
                    b.Property<decimal>("UserSUID")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("ChatSUID")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("UserRole")
                        .HasColumnType("integer");

                    b.HasKey("UserSUID", "ChatSUID");

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("MessengerServer.User", b =>
                {
                    b.Property<decimal>("SUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("SUID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MessengerServer.UserDevices", b =>
                {
                    b.Property<decimal>("UserSUID")
                        .HasColumnType("numeric(20,0)");

                    b.Property<byte>("deviceID")
                        .HasColumnType("smallint");

                    b.Property<decimal>("sessionID")
                        .HasColumnType("numeric(20,0)");

                    b.Property<bool>("isSynced")
                        .HasColumnType("boolean");

                    b.HasKey("UserSUID", "deviceID", "sessionID");

                    b.ToTable("UserDevices");
                });
#pragma warning restore 612, 618
        }
    }
}
